## _**Veri Bilimi İçin Programlama Dersi Ödev 2**_
### _Süheyl Çavuşoğlu_
_Açıklama: Bu ödevde “numpy” modülü ile ilgili soruların cevaplarını içeren bir Jupyter Notebook oluşturmanız beklenmektedir. Sorular birbirinden bağımsızdır ve eşit puanlıdır._

1-) A= [1,2,0,0,4,0] listesinde sıfır olmayan öğelerin indislerini bulunuz.

In [1]:
import numpy as np

A = [1,2,0,0,4,0] # İçerisinde 6 eleman olan bir liste oluşturuyoruz ve bunu A değişkenine atıyoruz.
indisler = np.nonzero(A) # nonzero metodu ile A listesindeki sıfır olmayan öğelerin indislerini buluyoruz ve bunu 'indisler' değişkenine atıyoruz.
print(indisler) # indisler değişkenini ekrana yazdırıyoruz.

(array([0, 1, 4], dtype=int64),)


2-) 30 elemanlı rastgele bir vektör oluşturunuz ve bu vektör elemanlarının ortalama değerini bulunuz.

In [2]:
import numpy as np

# random.randint metodunu kullanarak rastgele 30 eleman oluşturuyoruz ve bu elemanları 'a' değişkenine atıyoruz.
a = np.random.randint(low=-999, high=999, size=30)
#print(a)
# mean metodu ile de rastgele oluşturulan 30 elemanın ortalamasını buluyoruz ve bu bilgiyi 'mean' değişkenine atıyoruz.
mean = np.mean(a)
print(mean) # 30 elemanın ortalamasını ekrana yazdırıyoruz.

-181.9


3-) İki dizi arasındaki ortak değerleri bulan fonksiyonu tanımlayınız.

In [3]:
import numpy as np

arr1 = np.array([1,2,3,4,5]) # Birinci arrayimizi oluşturuyoruz ve 'arr1' değişkenine atıyoruz.
arr2 = np.array([3,4,5,6,7]) # İkinci arrayimizi oluşturuyoruz ve 'arr2' değişkenine atıyoruz.
intersect = np.intersect1d(arr1, arr2) # 'intersect1d' metodunu kulanarak iki arrayimizde ortak değerleri buluyoruz ve bunları intersect değişkenine atıyoruz.
print(intersect) # Ortak değerleri ekrana yazdırıyoruz.

[3 4 5]


4-) 10 elemanlı rastgele bir vektör oluşturunuz ve vektörün elemanları büyükten küçüğe doğru sıralayınız.

In [4]:
import numpy as np

# Bu sefer random.rand metodunu kullanarak 10 elemanlı bir rastgele dizi oluşturalım.
arr = np.random.randn(10)

# Daha sora sort metodunu kullanarak oluşturduğumuz diziyi büyükten küçüğe doğru sıralayalım ve bunun çıktısını 'sorted_arr' değişkenine atayalım.
sorted_arr = np.sort(arr)[::-1] # sort metodu ile küçükten büyüğe sıralandığı için biz bunu "::-1" ile tersine çevirdik yani büyükten küçüğe sıralamış olduk.

print(sorted_arr)  # Sonucu ekrana yazdıralım

[ 1.32761811  1.26169237  1.08443684  0.60381134  0.24306656 -0.14037387
 -0.50519922 -0.8131343  -1.11567643 -1.53232898]


5-) 6X6 boyutunda rastgele elemanlara sahip bir matris oluşturunuz ve bu matrisin satır ve sütunlarının ortalama değerlerini hesaplayınız.

In [5]:
import numpy as np

matris = np.random.rand(6, 6) # İlk olarak random.rand metodunu kullanarak, 6x6 boyutunda rastgele sayılardan oluşan bir matris oluşturuyoruz.
print(matris) # oluşturulan matrisi ekrana yazdırıp görelim.

satirlarin_ort = np.mean(matris, axis=1) # Daha sonra bizden istendiği şekilde, oluşturduğumuz matrisin her satırının ortalamasını hesaplayalım.

sutunlarin_ort = np.mean(matris, axis=0) # Sütunların ortalamasını hesaplayalım.

# ortalama değerleri yazdırın
print("Satırların ortalaması: {}".format(satirlarin_ort))
print("Sütunların ortalaması: {}".format(sutunlarin_ort))

[[0.66148698 0.66573035 0.56229006 0.69414146 0.66014699 0.01337017]
 [0.38149471 0.2091399  0.50474557 0.79683683 0.79636073 0.34604726]
 [0.8384197  0.24677695 0.09498487 0.02810807 0.4559936  0.49019293]
 [0.92890477 0.26061238 0.97422202 0.790246   0.03532188 0.88192401]
 [0.95041229 0.59514168 0.57445077 0.97599097 0.00172641 0.55125133]
 [0.50929707 0.39945643 0.34662616 0.66467107 0.59516664 0.95851479]]
Satırların ortalaması: [0.542861   0.50577083 0.35907935 0.64520517 0.60816224 0.57895536]
Sütunların ortalaması: [0.71166925 0.39614295 0.50955324 0.6583324  0.42411937 0.54021675]


6-) Tanımlanmış A=[1, 2, 3, 4, 5] vektörünün her değerin arasına ardışık 3 sıfır eklenmiş yeni bir vektör oluşturunuz.

In [6]:
import numpy as np

A = np.array([1, 2, 3, 4, 5]) # Vektörümüzü oluşturduk.

# Her değerin arasına 3 sıfır ekleyen vektörler oluşturduk.
B1 = np.insert(A, 1, [0,0,0])
B2 = np.insert(B1, 5, [0,0,0])
B3 = np.insert(B2, 9, [0,0,0])
B4 = np.insert(B3, 13, [0,0,0])
B5 = np.insert(B4, 17, [0,0,0])

# Sonuçları ekrana yazdırdık.
print("A  = ", A)
print("B1 = ", B1)
print("B2 = ", B2)
print("B3 = ", B3)
print("B4 = ", B4)
print("B5 = ", B5)

A  =  [1 2 3 4 5]
B1 =  [1 0 0 0 2 3 4 5]
B2 =  [1 0 0 0 2 0 0 0 3 4 5]
B3 =  [1 0 0 0 2 0 0 0 3 0 0 0 4 5]
B4 =  [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]
B5 =  [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5 0 0 0]


7-) Bir dizide en sık kullanılan değer bulan fonksiyonu yazınız.

In [7]:
import numpy as np

# Öncelikle bir array oluşturalım. 
arr = np.array([7, 2, 8, 9, 7, 6, 2, 4, 5, 1, 1, 8, 9, 0, 2])

# Daha sonra oluşturduğumuz arrayde en çok kullanılan değeri bulan bir fonksiyon yazalım.
def en_cok_kullanilan_deger(arr):
  # Arrayimizde en cok kullanılan değeri bulalım ve sayısını döndürelim.
  sayilar, sayi = np.unique(arr, return_counts=True)
  en_cok = sayilar[np.argmax(sayi)]
  return en_cok

en_cok_kullanilan = en_cok_kullanilan_deger(arr)

# Sonuçları yazdırın
print("Array:", arr)
print("Bu arrayde en çok kullanılan değer {}'dir".format(en_cok_kullanilan))

Array: [7 2 8 9 7 6 2 4 5 1 1 8 9 0 2]
Bu arrayde en çok kullanılan değer 2'dir


8-) Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] dizisini tanımlayınız. Z dizisini R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]] dizisi şekline dönüştürünüz.

In [8]:
import numpy as np

Z_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

Z = np.array(Z_list) # Z isminde 1'den 14'e kadar olan arrayimizi oluşturuyoruz.

R = np.array([Z[0:4], Z[1:5], Z[2:6], Z[3:7], Z[4:8], Z[5:9], Z[6:10],Z[7:11], Z[8:12], Z[9:13], Z[10:14]]) # Z arrayindeki elemanları ayırarak R arrayini oluşturduk.

print(R) # R arrayini ekrana yazdırdık.

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


9-) A = [9,2,3,2,5,4,12,4,5,6] ve B = [7,2,11,2,7,4,8,4,13,8] dizileri öğelerinin eşleştiği konumları elde ediniz.

In [9]:
import numpy as np

# Bizden istenen arrayleri oluşturuyoruz.
A = np.array([9,2,3,2,5,4,12,4,5,6])
B = np.array([7,2,11,2,7,4,8,4,13,8])

# Daha sonra oluşturulan iki array içerisinde birbiri ile eşleşen öğelerin indislerini belirlemek için where metodunu kullanıyoruz.
eslesme_olan_indisler = np.where(A == B)

# Eşleşen öğelerin indislerini ekrana yazdırıyoruz.
print(eslesme_olan_indisler)

(array([1, 3, 5, 7], dtype=int64),)


10-) 4X4 boyutunda rastgele elemanlara sahip bir matris oluşturunuz ve bu matrisin 2. Ve 3. Sütunlarının yerlerini bir hamlede değiştiriniz.

In [10]:
import numpy as np

arr = np.random.randn(4,4) # İlk olarak rastgele 4x4 boyutunda bir array oluşturalım.
print("İlk arrayimiz: ")
print(arr)                 # Oluşturduğumuz arrayi görmek için ekrana yazdıralım.

#Daha sonra oluşturulan arraydeki 2. ve 3. sütunların yerlerini değiştirelim.
arr[:, [1, 2]] = arr[:, [2, 1]]
print("2. ve 3. sütunlaırn yerleri değiştikten sonraki arrayimiz:")
print(arr) # Sütunların yerleri değiştikten sonraki arrayimizi ekrana yazdıralım.

İlk arrayimiz: 
[[-1.05117031  0.81470557  1.36429775  0.71599752]
 [-0.70639917 -0.74810625  1.05136596  0.7221496 ]
 [-0.58413892 -1.22472611 -0.03697961  0.30955142]
 [ 0.71975726  1.17139513  0.92383246  2.32097539]]
2. ve 3. sütunlaırn yerleri değiştikten sonraki arrayimiz:
[[-1.05117031  1.36429775  0.81470557  0.71599752]
 [-0.70639917  1.05136596 -0.74810625  0.7221496 ]
 [-0.58413892 -0.03697961 -1.22472611  0.30955142]
 [ 0.71975726  0.92383246  1.17139513  2.32097539]]
